// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/quiz.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionType int32

const (
	QuestionType_MULTIPLE_CHOICE QuestionType = 0
	QuestionType_TRUE_FALSE      QuestionType = 1
	QuestionType_REGION_SELECT   QuestionType = 2
	QuestionType_COMPARISON      QuestionType = 3
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0: "MULTIPLE_CHOICE",
		1: "TRUE_FALSE",
		2: "REGION_SELECT",
		3: "COMPARISON",
	}
	QuestionType_value = map[string]int32{
		"MULTIPLE_CHOICE": 0,
		"TRUE_FALSE":      1,
		"REGION_SELECT":   2,
		"COMPARISON":      3,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quiz_proto_enumTypes[0].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_proto_quiz_proto_enumTypes[0]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

type MediaType int32

const (
	MediaType_VIDEO MediaType = 0
	MediaType_IMAGE MediaType = 1
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "VIDEO",
		1: "IMAGE",
	}
	MediaType_value = map[string]int32{
		"VIDEO": 0,
		"IMAGE": 1,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quiz_proto_enumTypes[1].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_proto_quiz_proto_enumTypes[1]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

type GetRandomQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Difficulty    *string                `protobuf:"bytes,2,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	Type          *QuestionType          `protobuf:"varint,3,opt,name=type,proto3,enum=quiz.QuestionType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuestionRequest) Reset() {
	*x = GetRandomQuestionRequest{}
	mi := &file_proto_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuestionRequest) ProtoMessage() {}

func (x *GetRandomQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetRandomQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomQuestionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRandomQuestionRequest) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

func (x *GetRandomQuestionRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_MULTIPLE_CHOICE
}

type GetQuestionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionByIdRequest) Reset() {
	*x = GetQuestionByIdRequest{}
	mi := &file_proto_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionByIdRequest) ProtoMessage() {}

func (x *GetQuestionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuestionByIdRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type QuizQuestion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           QuestionType           `protobuf:"varint,2,opt,name=type,proto3,enum=quiz.QuestionType" json:"type,omitempty"`
	MediaType      MediaType              `protobuf:"varint,3,opt,name=media_type,json=mediaType,proto3,enum=quiz.MediaType" json:"media_type,omitempty"`
	MediaUrl       string                 `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	ThumbnailEmoji string                 `protobuf:"bytes,5,opt,name=thumbnail_emoji,json=thumbnailEmoji,proto3" json:"thumbnail_emoji,omitempty"`
	Difficulty     string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Category       string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Explanation    string                 `protobuf:"bytes,8,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Multiple Choice fields
	Options      []string `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	CorrectIndex *int32   `protobuf:"varint,11,opt,name=correct_index,json=correctIndex,proto3,oneof" json:"correct_index,omitempty"`
	// True/False fields
	CorrectAnswer *bool `protobuf:"varint,12,opt,name=correct_answer,json=correctAnswer,proto3,oneof" json:"correct_answer,omitempty"`
	// Region Select fields
	CorrectRegions []*Region `protobuf:"bytes,13,rep,name=correct_regions,json=correctRegions,proto3" json:"correct_regions,omitempty"`
	Tolerance      *int32    `protobuf:"varint,14,opt,name=tolerance,proto3,oneof" json:"tolerance,omitempty"`
	// Comparison fields
	ComparisonMediaUrl *string `protobuf:"bytes,15,opt,name=comparison_media_url,json=comparisonMediaUrl,proto3,oneof" json:"comparison_media_url,omitempty"`
	CorrectSide        *string `protobuf:"bytes,16,opt,name=correct_side,json=correctSide,proto3,oneof" json:"correct_side,omitempty"` // "left" or "right"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuizQuestion) Reset() {
	*x = QuizQuestion{}
	mi := &file_proto_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizQuestion) ProtoMessage() {}

func (x *QuizQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizQuestion.ProtoReflect.Descriptor instead.
func (*QuizQuestion) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *QuizQuestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizQuestion) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_MULTIPLE_CHOICE
}

func (x *QuizQuestion) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_VIDEO
}

func (x *QuizQuestion) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *QuizQuestion) GetThumbnailEmoji() string {
	if x != nil {
		return x.ThumbnailEmoji
	}
	return ""
}

func (x *QuizQuestion) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *QuizQuestion) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QuizQuestion) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *QuizQuestion) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuizQuestion) GetCorrectIndex() int32 {
	if x != nil && x.CorrectIndex != nil {
		return *x.CorrectIndex
	}
	return 0
}

func (x *QuizQuestion) GetCorrectAnswer() bool {
	if x != nil && x.CorrectAnswer != nil {
		return *x.CorrectAnswer
	}
	return false
}

func (x *QuizQuestion) GetCorrectRegions() []*Region {
	if x != nil {
		return x.CorrectRegions
	}
	return nil
}

func (x *QuizQuestion) GetTolerance() int32 {
	if x != nil && x.Tolerance != nil {
		return *x.Tolerance
	}
	return 0
}

func (x *QuizQuestion) GetComparisonMediaUrl() string {
	if x != nil && x.ComparisonMediaUrl != nil {
		return *x.ComparisonMediaUrl
	}
	return ""
}

func (x *QuizQuestion) GetCorrectSide() string {
	if x != nil && x.CorrectSide != nil {
		return *x.CorrectSide
	}
	return ""
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Radius        int32                  `protobuf:"varint,3,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_proto_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *Region) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Region) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Region) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type SubmitAnswerRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	// Multiple Choice
	SelectedIndex *int32 `protobuf:"varint,3,opt,name=selected_index,json=selectedIndex,proto3,oneof" json:"selected_index,omitempty"`
	// True/False
	SelectedAnswer *bool `protobuf:"varint,4,opt,name=selected_answer,json=selectedAnswer,proto3,oneof" json:"selected_answer,omitempty"`
	// Region Select
	SelectedRegion *Point `protobuf:"bytes,5,opt,name=selected_region,json=selectedRegion,proto3,oneof" json:"selected_region,omitempty"`
	// Comparison
	SelectedSide  *string `protobuf:"bytes,6,opt,name=selected_side,json=selectedSide,proto3,oneof" json:"selected_side,omitempty"` // "left" or "right"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_proto_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetSelectedIndex() int32 {
	if x != nil && x.SelectedIndex != nil {
		return *x.SelectedIndex
	}
	return 0
}

func (x *SubmitAnswerRequest) GetSelectedAnswer() bool {
	if x != nil && x.SelectedAnswer != nil {
		return *x.SelectedAnswer
	}
	return false
}

func (x *SubmitAnswerRequest) GetSelectedRegion() *Point {
	if x != nil {
		return x.SelectedRegion
	}
	return nil
}

func (x *SubmitAnswerRequest) GetSelectedSide() string {
	if x != nil && x.SelectedSide != nil {
		return *x.SelectedSide
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correct       bool                   `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	XpEarned      int32                  `protobuf:"varint,2,opt,name=xp_earned,json=xpEarned,proto3" json:"xp_earned,omitempty"`
	CoinsEarned   int32                  `protobuf:"varint,3,opt,name=coins_earned,json=coinsEarned,proto3" json:"coins_earned,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	StreakCount   int32                  `protobuf:"varint,5,opt,name=streak_count,json=streakCount,proto3" json:"streak_count,omitempty"`
	CorrectIndex  *int32                 `protobuf:"varint,6,opt,name=correct_index,json=correctIndex,proto3,oneof" json:"correct_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_proto_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitAnswerResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *SubmitAnswerResponse) GetXpEarned() int32 {
	if x != nil {
		return x.XpEarned
	}
	return 0
}

func (x *SubmitAnswerResponse) GetCoinsEarned() int32 {
	if x != nil {
		return x.CoinsEarned
	}
	return 0
}

func (x *SubmitAnswerResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SubmitAnswerResponse) GetStreakCount() int32 {
	if x != nil {
		return x.StreakCount
	}
	return 0
}

func (x *SubmitAnswerResponse) GetCorrectIndex() int32 {
	if x != nil && x.CorrectIndex != nil {
		return *x.CorrectIndex
	}
	return 0
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QuizStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAnswered int32                  `protobuf:"varint,1,opt,name=total_answered,json=totalAnswered,proto3" json:"total_answered,omitempty"`
	CorrectRate   float64                `protobuf:"fixed64,2,opt,name=correct_rate,json=correctRate,proto3" json:"correct_rate,omitempty"`
	CurrentStreak int32                  `protobuf:"varint,3,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	BestStreak    int32                  `protobuf:"varint,4,opt,name=best_streak,json=bestStreak,proto3" json:"best_streak,omitempty"`
	Lives         int32                  `protobuf:"varint,5,opt,name=lives,proto3" json:"lives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizStats) Reset() {
	*x = QuizStats{}
	mi := &file_proto_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizStats) ProtoMessage() {}

func (x *QuizStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizStats.ProtoReflect.Descriptor instead.
func (*QuizStats) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *QuizStats) GetTotalAnswered() int32 {
	if x != nil {
		return x.TotalAnswered
	}
	return 0
}

func (x *QuizStats) GetCorrectRate() float64 {
	if x != nil {
		return x.CorrectRate
	}
	return 0
}

func (x *QuizStats) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *QuizStats) GetBestStreak() int32 {
	if x != nil {
		return x.BestStreak
	}
	return 0
}

func (x *QuizStats) GetLives() int32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

var File_proto_quiz_proto protoreflect.FileDescriptor

const file_proto_quiz_proto_rawDesc = "" +
	"\n" +
	"\x10proto/quiz.proto\x12\x04quiz\"\x9d\x01\n" +
	"\x18GetRandomQuestionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\tH\x00R\n" +
	"difficulty\x88\x01\x01\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.quiz.QuestionTypeH\x01R\x04type\x88\x01\x01B\r\n" +
	"\v_difficultyB\a\n" +
	"\x05_type\"9\n" +
	"\x16GetQuestionByIdRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"\xa0\x05\n" +
	"\fQuizQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.quiz.QuestionTypeR\x04type\x12.\n" +
	"\n" +
	"media_type\x18\x03 \x01(\x0e2\x0f.quiz.MediaTypeR\tmediaType\x12\x1b\n" +
	"\tmedia_url\x18\x04 \x01(\tR\bmediaUrl\x12'\n" +
	"\x0fthumbnail_emoji\x18\x05 \x01(\tR\x0ethumbnailEmoji\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tR\n" +
	"difficulty\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12 \n" +
	"\vexplanation\x18\b \x01(\tR\vexplanation\x12\x18\n" +
	"\aoptions\x18\n" +
	" \x03(\tR\aoptions\x12(\n" +
	"\rcorrect_index\x18\v \x01(\x05H\x00R\fcorrectIndex\x88\x01\x01\x12*\n" +
	"\x0ecorrect_answer\x18\f \x01(\bH\x01R\rcorrectAnswer\x88\x01\x01\x125\n" +
	"\x0fcorrect_regions\x18\r \x03(\v2\f.quiz.RegionR\x0ecorrectRegions\x12!\n" +
	"\ttolerance\x18\x0e \x01(\x05H\x02R\ttolerance\x88\x01\x01\x125\n" +
	"\x14comparison_media_url\x18\x0f \x01(\tH\x03R\x12comparisonMediaUrl\x88\x01\x01\x12&\n" +
	"\fcorrect_side\x18\x10 \x01(\tH\x04R\vcorrectSide\x88\x01\x01B\x10\n" +
	"\x0e_correct_indexB\x11\n" +
	"\x0f_correct_answerB\f\n" +
	"\n" +
	"_toleranceB\x17\n" +
	"\x15_comparison_media_urlB\x0f\n" +
	"\r_correct_side\"<\n" +
	"\x06Region\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x05R\x06radius\"\xdb\x02\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12*\n" +
	"\x0eselected_index\x18\x03 \x01(\x05H\x00R\rselectedIndex\x88\x01\x01\x12,\n" +
	"\x0fselected_answer\x18\x04 \x01(\bH\x01R\x0eselectedAnswer\x88\x01\x01\x129\n" +
	"\x0fselected_region\x18\x05 \x01(\v2\v.quiz.PointH\x02R\x0eselectedRegion\x88\x01\x01\x12(\n" +
	"\rselected_side\x18\x06 \x01(\tH\x03R\fselectedSide\x88\x01\x01B\x11\n" +
	"\x0f_selected_indexB\x12\n" +
	"\x10_selected_answerB\x12\n" +
	"\x10_selected_regionB\x10\n" +
	"\x0e_selected_side\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xb5\x01\n" +
	"\x14SubmitAnswerResponse\x12\x18\n" +
	"\acorrect\x18\x01 \x01(\bR\acorrect\x12\x1b\n" +
	"\txp_earned\x18\x02 \x01(\x05R\bxpEarned\x12!\n" +
	"\fcoins_earned\x18\x03 \x01(\x05R\vcoinsEarned\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12!\n" +
	"\fstreak_count\x18\x05 \x01(\x05R\vstreakCount\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb3\x01\n" +
	"\tQuizStats\x12%\n" +
	"\x0etotal_answered\x18\x01 \x01(\x05R\rtotalAnswered\x12!\n" +
	"\fcorrect_rate\x18\x02 \x01(\x01R\vcorrectRate\x12%\n" +
	"\x0ecurrent_streak\x18\x03 \x01(\x05R\rcurrentStreak\x12\x1f\n" +
	"\vbest_streak\x18\x04 \x01(\x05R\n" +
	"bestStreak\x12\x14\n" +
	"\x05lives\x18\x05 \x01(\x05R\x05lives*V\n" +
	"\fQuestionType\x12\x13\n" +
	"\x0fMULTIPLE_CHOICE\x10\x00\x12\x0e\n" +
	"\n" +
	"TRUE_FALSE\x10\x01\x12\x11\n" +
	"\rREGION_SELECT\x10\x02\x12\x0e\n" +
	"\n" +
	"COMPARISON\x10\x03*!\n" +
	"\tMediaType\x12\t\n" +
	"\x05VIDEO\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x012\x9e\x02\n" +
	"\vQuizService\x12G\n" +
	"\x11GetRandomQuestion\x12\x1e.quiz.GetRandomQuestionRequest\x1a\x12.quiz.QuizQuestion\x12E\n" +
	"\fSubmitAnswer\x12\x19.quiz.SubmitAnswerRequest\x1a\x1a.quiz.SubmitAnswerResponse\x12:\n" +
	"\fGetUserStats\x12\x19.quiz.GetUserStatsRequest\x1a\x0f.quiz.QuizStats\x12C\n" +
	"\x0fGetQuestionById\x12\x1c.quiz.GetQuestionByIdRequest\x1a\x12.quiz.QuizQuestionB.Z,github.com/pawfiler/backend/services/quiz/pbb\x06proto3"

var (
	file_proto_quiz_proto_rawDescOnce sync.Once
	file_proto_quiz_proto_rawDescData []byte
)

func file_proto_quiz_proto_rawDescGZIP() []byte {
	file_proto_quiz_proto_rawDescOnce.Do(func() {
		file_proto_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)))
	})
	return file_proto_quiz_proto_rawDescData
}

var file_proto_quiz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_quiz_proto_goTypes = []any{
	(QuestionType)(0),                // 0: quiz.QuestionType
	(MediaType)(0),                   // 1: quiz.MediaType
	(*GetRandomQuestionRequest)(nil), // 2: quiz.GetRandomQuestionRequest
	(*GetQuestionByIdRequest)(nil),   // 3: quiz.GetQuestionByIdRequest
	(*QuizQuestion)(nil),             // 4: quiz.QuizQuestion
	(*Region)(nil),                   // 5: quiz.Region
	(*SubmitAnswerRequest)(nil),      // 6: quiz.SubmitAnswerRequest
	(*Point)(nil),                    // 7: quiz.Point
	(*SubmitAnswerResponse)(nil),     // 8: quiz.SubmitAnswerResponse
	(*GetUserStatsRequest)(nil),      // 9: quiz.GetUserStatsRequest
	(*QuizStats)(nil),                // 10: quiz.QuizStats
}
var file_proto_quiz_proto_depIdxs = []int32{
	0,  // 0: quiz.GetRandomQuestionRequest.type:type_name -> quiz.QuestionType
	0,  // 1: quiz.QuizQuestion.type:type_name -> quiz.QuestionType
	1,  // 2: quiz.QuizQuestion.media_type:type_name -> quiz.MediaType
	5,  // 3: quiz.QuizQuestion.correct_regions:type_name -> quiz.Region
	7,  // 4: quiz.SubmitAnswerRequest.selected_region:type_name -> quiz.Point
	2,  // 5: quiz.QuizService.GetRandomQuestion:input_type -> quiz.GetRandomQuestionRequest
	6,  // 6: quiz.QuizService.SubmitAnswer:input_type -> quiz.SubmitAnswerRequest
	9,  // 7: quiz.QuizService.GetUserStats:input_type -> quiz.GetUserStatsRequest
	3,  // 8: quiz.QuizService.GetQuestionById:input_type -> quiz.GetQuestionByIdRequest
	4,  // 9: quiz.QuizService.GetRandomQuestion:output_type -> quiz.QuizQuestion
	8,  // 10: quiz.QuizService.SubmitAnswer:output_type -> quiz.SubmitAnswerResponse
	10, // 11: quiz.QuizService.GetUserStats:output_type -> quiz.QuizStats
	4,  // 12: quiz.QuizService.GetQuestionById:output_type -> quiz.QuizQuestion
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_quiz_proto_init() }
func file_proto_quiz_proto_init() {
	if File_proto_quiz_proto != nil {
		return
	}
	file_proto_quiz_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_quiz_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_quiz_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quiz_proto_goTypes,
		DependencyIndexes: file_proto_quiz_proto_depIdxs,
		EnumInfos:         file_proto_quiz_proto_enumTypes,
		MessageInfos:      file_proto_quiz_proto_msgTypes,
	}.Build()
	File_proto_quiz_proto = out.File
	file_proto_quiz_proto_goTypes = nil
	file_proto_quiz_proto_depIdxs = nil
}
