apiVersion: v1
kind: Secret
metadata:
  name: pawfiler-db-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}?sslmode=require"
  DB_HOST: "{{ .Values.db.host }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
  DB_NAME: "{{ .Values.db.name }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: pawfiler-aws-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  AWS_REGION: "{{ .Values.aws.region }}"
  S3_BUCKET: "{{ .Values.aws.s3Bucket }}"
  CLOUDFRONT_DOMAIN: "{{ .Values.aws.cloudfrontDomain }}"
