#!/bin/bash
# 벡터 DB 구축 가이드

echo "🚀 PawFiler 벡터 DB 구축 가이드"
echo ""
echo "📋 필요한 정보:"
echo "  - RDS Endpoint: pawfiler-db-instance.c9osquca0esm.ap-northeast-2.rds.amazonaws.com"
echo "  - Bastion IP: 13.125.64.130"
echo "  - DB Name: pawfiler_db"
echo "  - DB User: pawfiler"
echo "  - DB Password: (필요)"
echo "  - SSH Key: silver-guardian-key.pem (필요)"
echo ""
echo "📝 실행 단계:"
echo ""
echo "1️⃣  SSH 키 확인"
echo "   위치: ~/Downloads/silver-guardian-key.pem 또는 다른 위치"
echo "   권한 설정: chmod 400 ~/Downloads/silver-guardian-key.pem"
echo ""
echo "2️⃣  Bastion을 통한 포트 포워딩"
echo "   ssh -i ~/Downloads/silver-guardian-key.pem -L 5432:pawfiler-db-instance.c9osquca0esm.ap-northeast-2.rds.amazonaws.com:5432 ec2-user@13.125.64.130"
echo ""
echo "3️⃣  새 터미널에서 psql 접속"
echo "   psql -h localhost -p 5432 -U pawfiler -d pawfiler_db"
echo "   (비밀번호 입력)"
echo ""
echo "4️⃣  벡터 DB 스크립트 실행"
echo "   \\i backend/scripts/setup-vector-db.sql"
echo ""
echo "5️⃣  확인"
echo "   \\dt agent_core.*"
echo "   \\dt quiz.user_skill_vectors"
echo "   \\dt community.post_embeddings"
echo ""
echo "✅ 완료 후 확인사항:"
echo "   - pgvector 확장 설치 확인: SELECT * FROM pg_extension WHERE extname = 'vector';"
echo "   - 테이블 생성 확인: SELECT count(*) FROM information_schema.tables WHERE table_schema = 'agent_core';"
echo "   - 인덱스 생성 확인: SELECT indexname FROM pg_indexes WHERE schemaname = 'agent_core';"
echo ""
echo "💡 대안: Docker를 통한 접속"
echo "   docker run -it --rm postgres:16 psql -h host.docker.internal -p 5432 -U pawfiler -d pawfiler_db"
echo ""
