// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user.proto

package userpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname       string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarEmoji    string                 `protobuf:"bytes,3,opt,name=avatar_emoji,json=avatarEmoji,proto3" json:"avatar_emoji,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	TierName       string                 `protobuf:"bytes,5,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
	TotalExp       int32                  `protobuf:"varint,6,opt,name=total_exp,json=totalExp,proto3" json:"total_exp,omitempty"`
	TotalCoins     int32                  `protobuf:"varint,7,opt,name=total_coins,json=totalCoins,proto3" json:"total_coins,omitempty"`
	Energy         int32                  `protobuf:"varint,8,opt,name=energy,proto3" json:"energy,omitempty"`
	MaxEnergy      int32                  `protobuf:"varint,9,opt,name=max_energy,json=maxEnergy,proto3" json:"max_energy,omitempty"`
	TotalQuizzes   int32                  `protobuf:"varint,10,opt,name=total_quizzes,json=totalQuizzes,proto3" json:"total_quizzes,omitempty"`
	CorrectRate    float64                `protobuf:"fixed64,11,opt,name=correct_rate,json=correctRate,proto3" json:"correct_rate,omitempty"`
	TotalAnalysis  int32                  `protobuf:"varint,12,opt,name=total_analysis,json=totalAnalysis,proto3" json:"total_analysis,omitempty"`
	CommunityPosts int32                  `protobuf:"varint,13,opt,name=community_posts,json=communityPosts,proto3" json:"community_posts,omitempty"`
	CurrentStreak  int32                  `protobuf:"varint,14,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	BestStreak     int32                  `protobuf:"varint,15,opt,name=best_streak,json=bestStreak,proto3" json:"best_streak,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetAvatarEmoji() string {
	if x != nil {
		return x.AvatarEmoji
	}
	return ""
}

func (x *UserProfile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserProfile) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

func (x *UserProfile) GetTotalExp() int32 {
	if x != nil {
		return x.TotalExp
	}
	return 0
}

func (x *UserProfile) GetTotalCoins() int32 {
	if x != nil {
		return x.TotalCoins
	}
	return 0
}

func (x *UserProfile) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *UserProfile) GetMaxEnergy() int32 {
	if x != nil {
		return x.MaxEnergy
	}
	return 0
}

func (x *UserProfile) GetTotalQuizzes() int32 {
	if x != nil {
		return x.TotalQuizzes
	}
	return 0
}

func (x *UserProfile) GetCorrectRate() float64 {
	if x != nil {
		return x.CorrectRate
	}
	return 0
}

func (x *UserProfile) GetTotalAnalysis() int32 {
	if x != nil {
		return x.TotalAnalysis
	}
	return 0
}

func (x *UserProfile) GetCommunityPosts() int32 {
	if x != nil {
		return x.CommunityPosts
	}
	return 0
}

func (x *UserProfile) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *UserProfile) GetBestStreak() int32 {
	if x != nil {
		return x.BestStreak
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	AvatarEmoji   *string                `protobuf:"bytes,3,opt,name=avatar_emoji,json=avatarEmoji,proto3,oneof" json:"avatar_emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarEmoji() string {
	if x != nil && x.AvatarEmoji != nil {
		return *x.AvatarEmoji
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarEmoji   string                 `protobuf:"bytes,3,opt,name=avatar_emoji,json=avatarEmoji,proto3" json:"avatar_emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProfileResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileResponse) GetAvatarEmoji() string {
	if x != nil {
		return x.AvatarEmoji
	}
	return ""
}

type GetRecentActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentActivitiesRequest) Reset() {
	*x = GetRecentActivitiesRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentActivitiesRequest) ProtoMessage() {}

func (x *GetRecentActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetRecentActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecentActivitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icon          string                 `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Xp            int32                  `protobuf:"varint,4,opt,name=xp,proto3" json:"xp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *Activity) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Activity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Activity) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Activity) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

type GetRecentActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentActivitiesResponse) Reset() {
	*x = GetRecentActivitiesResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentActivitiesResponse) ProtoMessage() {}

func (x *GetRecentActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentActivitiesResponse.ProtoReflect.Descriptor instead.
func (*GetRecentActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecentActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type GetShopItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopItemsRequest) Reset() {
	*x = GetShopItemsRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopItemsRequest) ProtoMessage() {}

func (x *GetShopItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopItemsRequest.ProtoReflect.Descriptor instead.
func (*GetShopItemsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Badge         string                 `protobuf:"bytes,6,opt,name=badge,proto3" json:"badge,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Bonus         int32                  `protobuf:"varint,9,opt,name=bonus,proto3" json:"bonus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ShopItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShopItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShopItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ShopItem) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *ShopItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ShopItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShopItem) GetBonus() int32 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

type GetShopItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ShopItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopItemsResponse) Reset() {
	*x = GetShopItemsResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopItemsResponse) ProtoMessage() {}

func (x *GetShopItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopItemsResponse.ProtoReflect.Descriptor instead.
func (*GetShopItemsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetShopItemsResponse) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PurchaseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItemRequest) Reset() {
	*x = PurchaseItemRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItemRequest) ProtoMessage() {}

func (x *PurchaseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItemRequest.ProtoReflect.Descriptor instead.
func (*PurchaseItemRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *PurchaseItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PurchaseItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type PurchaseItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	CoinsPaid     int32                  `protobuf:"varint,3,opt,name=coins_paid,json=coinsPaid,proto3" json:"coins_paid,omitempty"`
	TotalCoins    int32                  `protobuf:"varint,4,opt,name=total_coins,json=totalCoins,proto3" json:"total_coins,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItemResponse) Reset() {
	*x = PurchaseItemResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItemResponse) ProtoMessage() {}

func (x *PurchaseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItemResponse.ProtoReflect.Descriptor instead.
func (*PurchaseItemResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *PurchaseItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseItemResponse) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *PurchaseItemResponse) GetCoinsPaid() int32 {
	if x != nil {
		return x.CoinsPaid
	}
	return 0
}

func (x *PurchaseItemResponse) GetTotalCoins() int32 {
	if x != nil {
		return x.TotalCoins
	}
	return 0
}

func (x *PurchaseItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPurchaseHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseHistoryRequest) Reset() {
	*x = GetPurchaseHistoryRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseHistoryRequest) ProtoMessage() {}

func (x *GetPurchaseHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPurchaseHistoryRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetPurchaseHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Purchase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemType      string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	CoinsPaid     int32                  `protobuf:"varint,5,opt,name=coins_paid,json=coinsPaid,proto3" json:"coins_paid,omitempty"`
	PurchasedAt   string                 `protobuf:"bytes,6,opt,name=purchased_at,json=purchasedAt,proto3" json:"purchased_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *Purchase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Purchase) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Purchase) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Purchase) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *Purchase) GetCoinsPaid() int32 {
	if x != nil {
		return x.CoinsPaid
	}
	return 0
}

func (x *Purchase) GetPurchasedAt() string {
	if x != nil {
		return x.PurchasedAt
	}
	return ""
}

type GetPurchaseHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*Purchase            `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseHistoryResponse) Reset() {
	*x = GetPurchaseHistoryResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseHistoryResponse) ProtoMessage() {}

func (x *GetPurchaseHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPurchaseHistoryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetPurchaseHistoryResponse) GetPurchases() []*Purchase {
	if x != nil {
		return x.Purchases
	}
	return nil
}

type AddRewardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XpDelta       int32                  `protobuf:"varint,2,opt,name=xp_delta,json=xpDelta,proto3" json:"xp_delta,omitempty"`
	CoinDelta     int32                  `protobuf:"varint,3,opt,name=coin_delta,json=coinDelta,proto3" json:"coin_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRewardsRequest) Reset() {
	*x = AddRewardsRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRewardsRequest) ProtoMessage() {}

func (x *AddRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRewardsRequest.ProtoReflect.Descriptor instead.
func (*AddRewardsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *AddRewardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddRewardsRequest) GetXpDelta() int32 {
	if x != nil {
		return x.XpDelta
	}
	return 0
}

func (x *AddRewardsRequest) GetCoinDelta() int32 {
	if x != nil {
		return x.CoinDelta
	}
	return 0
}

type AddRewardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalExp      int32                  `protobuf:"varint,2,opt,name=total_exp,json=totalExp,proto3" json:"total_exp,omitempty"`
	TotalCoins    int32                  `protobuf:"varint,3,opt,name=total_coins,json=totalCoins,proto3" json:"total_coins,omitempty"`
	TierName      string                 `protobuf:"bytes,4,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRewardsResponse) Reset() {
	*x = AddRewardsResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRewardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRewardsResponse) ProtoMessage() {}

func (x *AddRewardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRewardsResponse.ProtoReflect.Descriptor instead.
func (*AddRewardsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *AddRewardsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRewardsResponse) GetTotalExp() int32 {
	if x != nil {
		return x.TotalExp
	}
	return 0
}

func (x *AddRewardsResponse) GetTotalCoins() int32 {
	if x != nil {
		return x.TotalCoins
	}
	return 0
}

func (x *AddRewardsResponse) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

func (x *AddRewardsResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xed\x03\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12!\n" +
	"\favatar_emoji\x18\x03 \x01(\tR\vavatarEmoji\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1b\n" +
	"\ttier_name\x18\x05 \x01(\tR\btierName\x12\x1b\n" +
	"\ttotal_exp\x18\x06 \x01(\x05R\btotalExp\x12\x1f\n" +
	"\vtotal_coins\x18\a \x01(\x05R\n" +
	"totalCoins\x12\x16\n" +
	"\x06energy\x18\b \x01(\x05R\x06energy\x12\x1d\n" +
	"\n" +
	"max_energy\x18\t \x01(\x05R\tmaxEnergy\x12#\n" +
	"\rtotal_quizzes\x18\n" +
	" \x01(\x05R\ftotalQuizzes\x12!\n" +
	"\fcorrect_rate\x18\v \x01(\x01R\vcorrectRate\x12%\n" +
	"\x0etotal_analysis\x18\f \x01(\x05R\rtotalAnalysis\x12'\n" +
	"\x0fcommunity_posts\x18\r \x01(\x05R\x0ecommunityPosts\x12%\n" +
	"\x0ecurrent_streak\x18\x0e \x01(\x05R\rcurrentStreak\x12\x1f\n" +
	"\vbest_streak\x18\x0f \x01(\x05R\n" +
	"bestStreak\"\x96\x01\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tH\x00R\bnickname\x88\x01\x01\x12&\n" +
	"\favatar_emoji\x18\x03 \x01(\tH\x01R\vavatarEmoji\x88\x01\x01B\v\n" +
	"\t_nicknameB\x0f\n" +
	"\r_avatar_emoji\"p\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12!\n" +
	"\favatar_emoji\x18\x03 \x01(\tR\vavatarEmoji\"5\n" +
	"\x1aGetRecentActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"X\n" +
	"\bActivity\x12\x12\n" +
	"\x04icon\x18\x01 \x01(\tR\x04icon\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x0e\n" +
	"\x02xp\x18\x04 \x01(\x05R\x02xp\"M\n" +
	"\x1bGetRecentActivitiesResponse\x12.\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x0e.user.ActivityR\n" +
	"activities\"\x15\n" +
	"\x13GetShopItemsRequest\"\xd6\x01\n" +
	"\bShopItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05badge\x18\x06 \x01(\tR\x05badge\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x05R\bquantity\x12\x14\n" +
	"\x05bonus\x18\t \x01(\x05R\x05bonus\"<\n" +
	"\x14GetShopItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.user.ShopItemR\x05items\"G\n" +
	"\x13PurchaseItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"\xa3\x01\n" +
	"\x14PurchaseItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"coins_paid\x18\x03 \x01(\x05R\tcoinsPaid\x12\x1f\n" +
	"\vtotal_coins\x18\x04 \x01(\x05R\n" +
	"totalCoins\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"4\n" +
	"\x19GetPurchaseHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xaf\x01\n" +
	"\bPurchase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x1d\n" +
	"\n" +
	"coins_paid\x18\x05 \x01(\x05R\tcoinsPaid\x12!\n" +
	"\fpurchased_at\x18\x06 \x01(\tR\vpurchasedAt\"J\n" +
	"\x1aGetPurchaseHistoryResponse\x12,\n" +
	"\tpurchases\x18\x01 \x03(\v2\x0e.user.PurchaseR\tpurchases\"f\n" +
	"\x11AddRewardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bxp_delta\x18\x02 \x01(\x05R\axpDelta\x12\x1d\n" +
	"\n" +
	"coin_delta\x18\x03 \x01(\x05R\tcoinDelta\"\x9f\x01\n" +
	"\x12AddRewardsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttotal_exp\x18\x02 \x01(\x05R\btotalExp\x12\x1f\n" +
	"\vtotal_coins\x18\x03 \x01(\x05R\n" +
	"totalCoins\x12\x1b\n" +
	"\ttier_name\x18\x04 \x01(\tR\btierName\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level2\xce\x06\n" +
	"\vUserService\x12a\n" +
	"\n" +
	"GetProfile\x12\x17.user.GetProfileRequest\x1a\x11.user.UserProfile\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/user.UserService/GetProfile\x12t\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x1b.user.UpdateProfileResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/user.UserService/UpdateProfile\x12\x8c\x01\n" +
	"\x13GetRecentActivities\x12 .user.GetRecentActivitiesRequest\x1a!.user.GetRecentActivitiesResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/user.UserService/GetRecentActivities\x12p\n" +
	"\fGetShopItems\x12\x19.user.GetShopItemsRequest\x1a\x1a.user.GetShopItemsResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/user.UserService/GetShopItems\x12p\n" +
	"\fPurchaseItem\x12\x19.user.PurchaseItemRequest\x1a\x1a.user.PurchaseItemResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/user.UserService/PurchaseItem\x12\x88\x01\n" +
	"\x12GetPurchaseHistory\x12\x1f.user.GetPurchaseHistoryRequest\x1a .user.GetPurchaseHistoryResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/user.UserService/GetPurchaseHistory\x12h\n" +
	"\n" +
	"AddRewards\x12\x17.user.AddRewardsRequest\x1a\x18.user.AddRewardsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/user.UserService/AddRewardsB\x11Z\x0fuser-service/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_user_proto_goTypes = []any{
	(*GetProfileRequest)(nil),           // 0: user.GetProfileRequest
	(*UserProfile)(nil),                 // 1: user.UserProfile
	(*UpdateProfileRequest)(nil),        // 2: user.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 3: user.UpdateProfileResponse
	(*GetRecentActivitiesRequest)(nil),  // 4: user.GetRecentActivitiesRequest
	(*Activity)(nil),                    // 5: user.Activity
	(*GetRecentActivitiesResponse)(nil), // 6: user.GetRecentActivitiesResponse
	(*GetShopItemsRequest)(nil),         // 7: user.GetShopItemsRequest
	(*ShopItem)(nil),                    // 8: user.ShopItem
	(*GetShopItemsResponse)(nil),        // 9: user.GetShopItemsResponse
	(*PurchaseItemRequest)(nil),         // 10: user.PurchaseItemRequest
	(*PurchaseItemResponse)(nil),        // 11: user.PurchaseItemResponse
	(*GetPurchaseHistoryRequest)(nil),   // 12: user.GetPurchaseHistoryRequest
	(*Purchase)(nil),                    // 13: user.Purchase
	(*GetPurchaseHistoryResponse)(nil),  // 14: user.GetPurchaseHistoryResponse
	(*AddRewardsRequest)(nil),           // 15: user.AddRewardsRequest
	(*AddRewardsResponse)(nil),          // 16: user.AddRewardsResponse
}
var file_user_proto_depIdxs = []int32{
	5,  // 0: user.GetRecentActivitiesResponse.activities:type_name -> user.Activity
	8,  // 1: user.GetShopItemsResponse.items:type_name -> user.ShopItem
	13, // 2: user.GetPurchaseHistoryResponse.purchases:type_name -> user.Purchase
	0,  // 3: user.UserService.GetProfile:input_type -> user.GetProfileRequest
	2,  // 4: user.UserService.UpdateProfile:input_type -> user.UpdateProfileRequest
	4,  // 5: user.UserService.GetRecentActivities:input_type -> user.GetRecentActivitiesRequest
	7,  // 6: user.UserService.GetShopItems:input_type -> user.GetShopItemsRequest
	10, // 7: user.UserService.PurchaseItem:input_type -> user.PurchaseItemRequest
	12, // 8: user.UserService.GetPurchaseHistory:input_type -> user.GetPurchaseHistoryRequest
	15, // 9: user.UserService.AddRewards:input_type -> user.AddRewardsRequest
	1,  // 10: user.UserService.GetProfile:output_type -> user.UserProfile
	3,  // 11: user.UserService.UpdateProfile:output_type -> user.UpdateProfileResponse
	6,  // 12: user.UserService.GetRecentActivities:output_type -> user.GetRecentActivitiesResponse
	9,  // 13: user.UserService.GetShopItems:output_type -> user.GetShopItemsResponse
	11, // 14: user.UserService.PurchaseItem:output_type -> user.PurchaseItemResponse
	14, // 15: user.UserService.GetPurchaseHistory:output_type -> user.GetPurchaseHistoryResponse
	16, // 16: user.UserService.AddRewards:output_type -> user.AddRewardsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}

