// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetProfile_FullMethodName          = "/user.UserService/GetProfile"
	UserService_UpdateProfile_FullMethodName       = "/user.UserService/UpdateProfile"
	UserService_GetRecentActivities_FullMethodName = "/user.UserService/GetRecentActivities"
	UserService_GetShopItems_FullMethodName        = "/user.UserService/GetShopItems"
	UserService_PurchaseItem_FullMethodName        = "/user.UserService/PurchaseItem"
	UserService_GetPurchaseHistory_FullMethodName  = "/user.UserService/GetPurchaseHistory"
	UserService_AddRewards_FullMethodName          = "/user.UserService/AddRewards"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	GetRecentActivities(ctx context.Context, in *GetRecentActivitiesRequest, opts ...grpc.CallOption) (*GetRecentActivitiesResponse, error)
	GetShopItems(ctx context.Context, in *GetShopItemsRequest, opts ...grpc.CallOption) (*GetShopItemsResponse, error)
	PurchaseItem(ctx context.Context, in *PurchaseItemRequest, opts ...grpc.CallOption) (*PurchaseItemResponse, error)
	GetPurchaseHistory(ctx context.Context, in *GetPurchaseHistoryRequest, opts ...grpc.CallOption) (*GetPurchaseHistoryResponse, error)
	AddRewards(ctx context.Context, in *AddRewardsRequest, opts ...grpc.CallOption) (*AddRewardsResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRecentActivities(ctx context.Context, in *GetRecentActivitiesRequest, opts ...grpc.CallOption) (*GetRecentActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentActivitiesResponse)
	err := c.cc.Invoke(ctx, UserService_GetRecentActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetShopItems(ctx context.Context, in *GetShopItemsRequest, opts ...grpc.CallOption) (*GetShopItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShopItemsResponse)
	err := c.cc.Invoke(ctx, UserService_GetShopItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PurchaseItem(ctx context.Context, in *PurchaseItemRequest, opts ...grpc.CallOption) (*PurchaseItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseItemResponse)
	err := c.cc.Invoke(ctx, UserService_PurchaseItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPurchaseHistory(ctx context.Context, in *GetPurchaseHistoryRequest, opts ...grpc.CallOption) (*GetPurchaseHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPurchaseHistoryResponse)
	err := c.cc.Invoke(ctx, UserService_GetPurchaseHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddRewards(ctx context.Context, in *AddRewardsRequest, opts ...grpc.CallOption) (*AddRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRewardsResponse)
	err := c.cc.Invoke(ctx, UserService_AddRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	GetProfile(context.Context, *GetProfileRequest) (*UserProfile, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	GetRecentActivities(context.Context, *GetRecentActivitiesRequest) (*GetRecentActivitiesResponse, error)
	GetShopItems(context.Context, *GetShopItemsRequest) (*GetShopItemsResponse, error)
	PurchaseItem(context.Context, *PurchaseItemRequest) (*PurchaseItemResponse, error)
	GetPurchaseHistory(context.Context, *GetPurchaseHistoryRequest) (*GetPurchaseHistoryResponse, error)
	AddRewards(context.Context, *AddRewardsRequest) (*AddRewardsResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetProfile(context.Context, *GetProfileRequest) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) GetRecentActivities(context.Context, *GetRecentActivitiesRequest) (*GetRecentActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentActivities not implemented")
}
func (UnimplementedUserServiceServer) GetShopItems(context.Context, *GetShopItemsRequest) (*GetShopItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopItems not implemented")
}
func (UnimplementedUserServiceServer) PurchaseItem(context.Context, *PurchaseItemRequest) (*PurchaseItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseItem not implemented")
}
func (UnimplementedUserServiceServer) GetPurchaseHistory(context.Context, *GetPurchaseHistoryRequest) (*GetPurchaseHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPurchaseHistory not implemented")
}
func (UnimplementedUserServiceServer) AddRewards(context.Context, *AddRewardsRequest) (*AddRewardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRewards not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRecentActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRecentActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetRecentActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRecentActivities(ctx, req.(*GetRecentActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetShopItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetShopItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetShopItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetShopItems(ctx, req.(*GetShopItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PurchaseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PurchaseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_PurchaseItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PurchaseItem(ctx, req.(*PurchaseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPurchaseHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPurchaseHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPurchaseHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPurchaseHistory(ctx, req.(*GetPurchaseHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddRewards(ctx, req.(*AddRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _UserService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetRecentActivities",
			Handler:    _UserService_GetRecentActivities_Handler,
		},
		{
			MethodName: "GetShopItems",
			Handler:    _UserService_GetShopItems_Handler,
		},
		{
			MethodName: "PurchaseItem",
			Handler:    _UserService_PurchaseItem_Handler,
		},
		{
			MethodName: "GetPurchaseHistory",
			Handler:    _UserService_GetPurchaseHistory_Handler,
		},
		{
			MethodName: "AddRewards",
			Handler:    _UserService_AddRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

