apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: admin
type: Opaque
stringData:
  host: "pawfiler-db-instance.c9osquca0esm.ap-northeast-2.rds.amazonaws.com"
  username: "pawfiler"
  password: "pawfiler"
