apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: admin
type: Opaque
stringData:
  host: "REPLACE_WITH_RDS_ENDPOINT"
  username: "pawfiler"
  password: "REPLACE_WITH_DB_PASSWORD"
