apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: quiz-service-dr
  namespace: {{ .Values.global.namespace }}
spec:
  host: quiz-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: community-service-dr
  namespace: {{ .Values.global.namespace }}
spec:
  host: community-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: admin-service-dr
  namespace: {{ .Values.global.namespace }}
spec:
  host: admin-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: envoy-dr
  namespace: {{ .Values.global.namespace }}
spec:
  host: envoy
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
