apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pawfiler

resources:
  - ../../rayservice.yaml
  - ../../hpa.yaml  # 개발 환경에서만 HPA 적용

patches:
  - patch: |-
      - op: replace
        path: /spec/rayClusterConfig/workerGroupSpecs/0/replicas
        value: 0  # 개발: 시작 시 0개
    target:
      kind: RayService
      name: pawfiler-serve
