// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: backend/proto/community.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthorNickname string                 `protobuf:"bytes,2,opt,name=author_nickname,json=authorNickname,proto3" json:"author_nickname,omitempty"`
	AuthorEmoji    string                 `protobuf:"bytes,3,opt,name=author_emoji,json=authorEmoji,proto3" json:"author_emoji,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostRequest) GetAuthorNickname() string {
	if x != nil {
		return x.AuthorNickname
	}
	return ""
}

func (x *CreatePostRequest) GetAuthorEmoji() string {
	if x != nil {
		return x.AuthorEmoji
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Post struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId       string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorNickname string                 `protobuf:"bytes,3,opt,name=author_nickname,json=authorNickname,proto3" json:"author_nickname,omitempty"`
	AuthorEmoji    string                 `protobuf:"bytes,4,opt,name=author_emoji,json=authorEmoji,proto3" json:"author_emoji,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Likes          int32                  `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments       int32                  `protobuf:"varint,8,opt,name=comments,proto3" json:"comments,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Tags           []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_backend_proto_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Post) GetAuthorNickname() string {
	if x != nil {
		return x.AuthorNickname
	}
	return ""
}

func (x *Post) GetAuthorEmoji() string {
	if x != nil {
		return x.AuthorEmoji
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Post) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Post) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *Post) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	SearchType    string                 `protobuf:"bytes,4,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"` // "title", "body", "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFeedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFeedRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetFeedRequest) GetSearchType() string {
	if x != nil {
		return x.SearchType
	}
	return ""
}

type FeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{3}
}

func (x *FeedResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *FeedResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *FeedResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{4}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{5}
}

func (x *LikePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *LikePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AlreadyLiked  bool                   `protobuf:"varint,2,opt,name=already_liked,json=alreadyLiked,proto3" json:"already_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{6}
}

func (x *LikePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikePostResponse) GetAlreadyLiked() bool {
	if x != nil {
		return x.AlreadyLiked
	}
	return false
}

type Comment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId         string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId       string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorNickname string                 `protobuf:"bytes,4,opt,name=author_nickname,json=authorNickname,proto3" json:"author_nickname,omitempty"`
	AuthorEmoji    string                 `protobuf:"bytes,5,opt,name=author_emoji,json=authorEmoji,proto3" json:"author_emoji,omitempty"`
	Body           string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_backend_proto_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{7}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Comment) GetAuthorNickname() string {
	if x != nil {
		return x.AuthorNickname
	}
	return ""
}

func (x *Comment) GetAuthorEmoji() string {
	if x != nil {
		return x.AuthorEmoji
	}
	return ""
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type CommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsResponse) Reset() {
	*x = CommentsResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsResponse) ProtoMessage() {}

func (x *CommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsResponse.ProtoReflect.Descriptor instead.
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{9}
}

func (x *CommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// UpdatePost
type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// DeletePost
type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CreateComment (rename AddCommentRequest)
type CreateCommentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PostId         string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthorNickname string                 `protobuf:"bytes,3,opt,name=author_nickname,json=authorNickname,proto3" json:"author_nickname,omitempty"`
	AuthorEmoji    string                 `protobuf:"bytes,4,opt,name=author_emoji,json=authorEmoji,proto3" json:"author_emoji,omitempty"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentRequest) GetAuthorNickname() string {
	if x != nil {
		return x.AuthorNickname
	}
	return ""
}

func (x *CreateCommentRequest) GetAuthorEmoji() string {
	if x != nil {
		return x.AuthorEmoji
	}
	return ""
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// DeleteComment
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// UnlikePost
type UnlikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{16}
}

func (x *UnlikePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UnlikePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UnlikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostResponse) Reset() {
	*x = UnlikePostResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostResponse) ProtoMessage() {}

func (x *UnlikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostResponse.ProtoReflect.Descriptor instead.
func (*UnlikePostResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{17}
}

func (x *UnlikePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CheckLike
type CheckLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLikeRequest) Reset() {
	*x = CheckLikeRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLikeRequest) ProtoMessage() {}

func (x *CheckLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLikeRequest.ProtoReflect.Descriptor instead.
func (*CheckLikeRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{18}
}

func (x *CheckLikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CheckLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLikeResponse) Reset() {
	*x = CheckLikeResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLikeResponse) ProtoMessage() {}

func (x *CheckLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLikeResponse.ProtoReflect.Descriptor instead.
func (*CheckLikeResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{19}
}

func (x *CheckLikeResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

// GetNotices
type GetNoticesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticesRequest) Reset() {
	*x = GetNoticesRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticesRequest) ProtoMessage() {}

func (x *GetNoticesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticesRequest.ProtoReflect.Descriptor instead.
func (*GetNoticesRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{20}
}

type Notice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_backend_proto_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{21}
}

func (x *Notice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type NoticesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notices       []*Notice              `protobuf:"bytes,1,rep,name=notices,proto3" json:"notices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticesResponse) Reset() {
	*x = NoticesResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticesResponse) ProtoMessage() {}

func (x *NoticesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticesResponse.ProtoReflect.Descriptor instead.
func (*NoticesResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{22}
}

func (x *NoticesResponse) GetNotices() []*Notice {
	if x != nil {
		return x.Notices
	}
	return nil
}

// GetTopDetective
type GetTopDetectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDetectiveRequest) Reset() {
	*x = GetTopDetectiveRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDetectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDetectiveRequest) ProtoMessage() {}

func (x *GetTopDetectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDetectiveRequest.ProtoReflect.Descriptor instead.
func (*GetTopDetectiveRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{23}
}

type TopDetectiveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthorNickname string                 `protobuf:"bytes,1,opt,name=author_nickname,json=authorNickname,proto3" json:"author_nickname,omitempty"`
	AuthorEmoji    string                 `protobuf:"bytes,2,opt,name=author_emoji,json=authorEmoji,proto3" json:"author_emoji,omitempty"`
	TotalLikes     int32                  `protobuf:"varint,3,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopDetectiveResponse) Reset() {
	*x = TopDetectiveResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopDetectiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopDetectiveResponse) ProtoMessage() {}

func (x *TopDetectiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopDetectiveResponse.ProtoReflect.Descriptor instead.
func (*TopDetectiveResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{24}
}

func (x *TopDetectiveResponse) GetAuthorNickname() string {
	if x != nil {
		return x.AuthorNickname
	}
	return ""
}

func (x *TopDetectiveResponse) GetAuthorEmoji() string {
	if x != nil {
		return x.AuthorEmoji
	}
	return ""
}

func (x *TopDetectiveResponse) GetTotalLikes() int32 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

// GetHotTopic
type GetHotTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotTopicRequest) Reset() {
	*x = GetHotTopicRequest{}
	mi := &file_backend_proto_community_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotTopicRequest) ProtoMessage() {}

func (x *GetHotTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotTopicRequest.ProtoReflect.Descriptor instead.
func (*GetHotTopicRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{25}
}

type HotTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotTopicResponse) Reset() {
	*x = HotTopicResponse{}
	mi := &file_backend_proto_community_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotTopicResponse) ProtoMessage() {}

func (x *HotTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_community_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotTopicResponse.ProtoReflect.Descriptor instead.
func (*HotTopicResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_community_proto_rawDescGZIP(), []int{26}
}

func (x *HotTopicResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *HotTopicResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_backend_proto_community_proto protoreflect.FileDescriptor

const file_backend_proto_community_proto_rawDesc = "" +
	"\n" +
	"\x1dbackend/proto/community.proto\x12\tcommunity\"\xb6\x01\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fauthor_nickname\x18\x02 \x01(\tR\x0eauthorNickname\x12!\n" +
	"\fauthor_emoji\x18\x03 \x01(\tR\vauthorEmoji\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\x8e\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12'\n" +
	"\x0fauthor_nickname\x18\x03 \x01(\tR\x0eauthorNickname\x12!\n" +
	"\fauthor_emoji\x18\x04 \x01(\tR\vauthorEmoji\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x14\n" +
	"\x05likes\x18\a \x01(\x05R\x05likes\x12\x1a\n" +
	"\bcomments\x18\b \x01(\x05R\bcomments\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\"\x85\x01\n" +
	"\x0eGetFeedRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x12\x1f\n" +
	"\vsearch_type\x18\x04 \x01(\tR\n" +
	"searchType\"j\n" +
	"\fFeedResponse\x12%\n" +
	"\x05posts\x18\x01 \x03(\v2\x0f.community.PostR\x05posts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\")\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"C\n" +
	"\x0fLikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Q\n" +
	"\x10LikePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\ralready_liked\x18\x02 \x01(\bR\falreadyLiked\"\xce\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12'\n" +
	"\x0fauthor_nickname\x18\x04 \x01(\tR\x0eauthorNickname\x12!\n" +
	"\fauthor_emoji\x18\x05 \x01(\tR\vauthorEmoji\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"-\n" +
	"\x12GetCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"B\n" +
	"\x10CommentsResponse\x12.\n" +
	"\bcomments\x18\x01 \x03(\v2\x12.community.CommentR\bcomments\"\x83\x01\n" +
	"\x11UpdatePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"E\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12DeletePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa8\x01\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fauthor_nickname\x18\x03 \x01(\tR\x0eauthorNickname\x12!\n" +
	"\fauthor_emoji\x18\x04 \x01(\tR\vauthorEmoji\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"N\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x11UnlikePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12UnlikePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x10CheckLikeRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\")\n" +
	"\x11CheckLikeResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"\x13\n" +
	"\x11GetNoticesRequest\".\n" +
	"\x06Notice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\">\n" +
	"\x0fNoticesResponse\x12+\n" +
	"\anotices\x18\x01 \x03(\v2\x11.community.NoticeR\anotices\"\x18\n" +
	"\x16GetTopDetectiveRequest\"\x83\x01\n" +
	"\x14TopDetectiveResponse\x12'\n" +
	"\x0fauthor_nickname\x18\x01 \x01(\tR\x0eauthorNickname\x12!\n" +
	"\fauthor_emoji\x18\x02 \x01(\tR\vauthorEmoji\x12\x1f\n" +
	"\vtotal_likes\x18\x03 \x01(\x05R\n" +
	"totalLikes\"\x14\n" +
	"\x12GetHotTopicRequest\":\n" +
	"\x10HotTopicResponse\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xf4\a\n" +
	"\x10CommunityService\x12=\n" +
	"\aGetFeed\x12\x19.community.GetFeedRequest\x1a\x17.community.FeedResponse\x125\n" +
	"\aGetPost\x12\x19.community.GetPostRequest\x1a\x0f.community.Post\x12;\n" +
	"\n" +
	"CreatePost\x12\x1c.community.CreatePostRequest\x1a\x0f.community.Post\x12;\n" +
	"\n" +
	"UpdatePost\x12\x1c.community.UpdatePostRequest\x1a\x0f.community.Post\x12I\n" +
	"\n" +
	"DeletePost\x12\x1c.community.DeletePostRequest\x1a\x1d.community.DeletePostResponse\x12I\n" +
	"\vGetComments\x12\x1d.community.GetCommentsRequest\x1a\x1b.community.CommentsResponse\x12D\n" +
	"\rCreateComment\x12\x1f.community.CreateCommentRequest\x1a\x12.community.Comment\x12R\n" +
	"\rDeleteComment\x12\x1f.community.DeleteCommentRequest\x1a .community.DeleteCommentResponse\x12C\n" +
	"\bLikePost\x12\x1a.community.LikePostRequest\x1a\x1b.community.LikePostResponse\x12I\n" +
	"\n" +
	"UnlikePost\x12\x1c.community.UnlikePostRequest\x1a\x1d.community.UnlikePostResponse\x12F\n" +
	"\tCheckLike\x12\x1b.community.CheckLikeRequest\x1a\x1c.community.CheckLikeResponse\x12F\n" +
	"\n" +
	"GetNotices\x12\x1c.community.GetNoticesRequest\x1a\x1a.community.NoticesResponse\x12U\n" +
	"\x0fGetTopDetective\x12!.community.GetTopDetectiveRequest\x1a\x1f.community.TopDetectiveResponse\x12I\n" +
	"\vGetHotTopic\x12\x1d.community.GetHotTopicRequest\x1a\x1b.community.HotTopicResponseB3Z1github.com/pawfiler/backend/services/community/pbb\x06proto3"

var (
	file_backend_proto_community_proto_rawDescOnce sync.Once
	file_backend_proto_community_proto_rawDescData []byte
)

func file_backend_proto_community_proto_rawDescGZIP() []byte {
	file_backend_proto_community_proto_rawDescOnce.Do(func() {
		file_backend_proto_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_community_proto_rawDesc), len(file_backend_proto_community_proto_rawDesc)))
	})
	return file_backend_proto_community_proto_rawDescData
}

var file_backend_proto_community_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_backend_proto_community_proto_goTypes = []any{
	(*CreatePostRequest)(nil),      // 0: community.CreatePostRequest
	(*Post)(nil),                   // 1: community.Post
	(*GetFeedRequest)(nil),         // 2: community.GetFeedRequest
	(*FeedResponse)(nil),           // 3: community.FeedResponse
	(*GetPostRequest)(nil),         // 4: community.GetPostRequest
	(*LikePostRequest)(nil),        // 5: community.LikePostRequest
	(*LikePostResponse)(nil),       // 6: community.LikePostResponse
	(*Comment)(nil),                // 7: community.Comment
	(*GetCommentsRequest)(nil),     // 8: community.GetCommentsRequest
	(*CommentsResponse)(nil),       // 9: community.CommentsResponse
	(*UpdatePostRequest)(nil),      // 10: community.UpdatePostRequest
	(*DeletePostRequest)(nil),      // 11: community.DeletePostRequest
	(*DeletePostResponse)(nil),     // 12: community.DeletePostResponse
	(*CreateCommentRequest)(nil),   // 13: community.CreateCommentRequest
	(*DeleteCommentRequest)(nil),   // 14: community.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),  // 15: community.DeleteCommentResponse
	(*UnlikePostRequest)(nil),      // 16: community.UnlikePostRequest
	(*UnlikePostResponse)(nil),     // 17: community.UnlikePostResponse
	(*CheckLikeRequest)(nil),       // 18: community.CheckLikeRequest
	(*CheckLikeResponse)(nil),      // 19: community.CheckLikeResponse
	(*GetNoticesRequest)(nil),      // 20: community.GetNoticesRequest
	(*Notice)(nil),                 // 21: community.Notice
	(*NoticesResponse)(nil),        // 22: community.NoticesResponse
	(*GetTopDetectiveRequest)(nil), // 23: community.GetTopDetectiveRequest
	(*TopDetectiveResponse)(nil),   // 24: community.TopDetectiveResponse
	(*GetHotTopicRequest)(nil),     // 25: community.GetHotTopicRequest
	(*HotTopicResponse)(nil),       // 26: community.HotTopicResponse
}
var file_backend_proto_community_proto_depIdxs = []int32{
	1,  // 0: community.FeedResponse.posts:type_name -> community.Post
	7,  // 1: community.CommentsResponse.comments:type_name -> community.Comment
	21, // 2: community.NoticesResponse.notices:type_name -> community.Notice
	2,  // 3: community.CommunityService.GetFeed:input_type -> community.GetFeedRequest
	4,  // 4: community.CommunityService.GetPost:input_type -> community.GetPostRequest
	0,  // 5: community.CommunityService.CreatePost:input_type -> community.CreatePostRequest
	10, // 6: community.CommunityService.UpdatePost:input_type -> community.UpdatePostRequest
	11, // 7: community.CommunityService.DeletePost:input_type -> community.DeletePostRequest
	8,  // 8: community.CommunityService.GetComments:input_type -> community.GetCommentsRequest
	13, // 9: community.CommunityService.CreateComment:input_type -> community.CreateCommentRequest
	14, // 10: community.CommunityService.DeleteComment:input_type -> community.DeleteCommentRequest
	5,  // 11: community.CommunityService.LikePost:input_type -> community.LikePostRequest
	16, // 12: community.CommunityService.UnlikePost:input_type -> community.UnlikePostRequest
	18, // 13: community.CommunityService.CheckLike:input_type -> community.CheckLikeRequest
	20, // 14: community.CommunityService.GetNotices:input_type -> community.GetNoticesRequest
	23, // 15: community.CommunityService.GetTopDetective:input_type -> community.GetTopDetectiveRequest
	25, // 16: community.CommunityService.GetHotTopic:input_type -> community.GetHotTopicRequest
	3,  // 17: community.CommunityService.GetFeed:output_type -> community.FeedResponse
	1,  // 18: community.CommunityService.GetPost:output_type -> community.Post
	1,  // 19: community.CommunityService.CreatePost:output_type -> community.Post
	1,  // 20: community.CommunityService.UpdatePost:output_type -> community.Post
	12, // 21: community.CommunityService.DeletePost:output_type -> community.DeletePostResponse
	9,  // 22: community.CommunityService.GetComments:output_type -> community.CommentsResponse
	7,  // 23: community.CommunityService.CreateComment:output_type -> community.Comment
	15, // 24: community.CommunityService.DeleteComment:output_type -> community.DeleteCommentResponse
	6,  // 25: community.CommunityService.LikePost:output_type -> community.LikePostResponse
	17, // 26: community.CommunityService.UnlikePost:output_type -> community.UnlikePostResponse
	19, // 27: community.CommunityService.CheckLike:output_type -> community.CheckLikeResponse
	22, // 28: community.CommunityService.GetNotices:output_type -> community.NoticesResponse
	24, // 29: community.CommunityService.GetTopDetective:output_type -> community.TopDetectiveResponse
	26, // 30: community.CommunityService.GetHotTopic:output_type -> community.HotTopicResponse
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_backend_proto_community_proto_init() }
func file_backend_proto_community_proto_init() {
	if File_backend_proto_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_community_proto_rawDesc), len(file_backend_proto_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_community_proto_goTypes,
		DependencyIndexes: file_backend_proto_community_proto_depIdxs,
		MessageInfos:      file_backend_proto_community_proto_msgTypes,
	}.Build()
	File_backend_proto_community_proto = out.File
	file_backend_proto_community_proto_goTypes = nil
	file_backend_proto_community_proto_depIdxs = nil
}
